### ISSUE TITLE
Mixins Not Working

### ISSUE THREAD

**Issue by coreDeiv** [ConnectThink/WP-SCSS#202]
I'm having a problem when compiling the scss styles with a `@mixin` for media queries, it turns out that it doesn't get the value of `$width` under the map of `$breakpoints`, and in the compiled CSS it says `@media only screen and (max-width: $width)`, I already checked locally with Gulp, Ruby and Webpack and if it performs the mixin function correctly, what could be happening?

The Mixin
```scss
@mixin mq($width, $type: max) {
  @if map_has_key($breakpoints, $width) {
      $width: map_get($breakpoints, $width);
      @if $type == min {
          $width: $width - 1px;
      }
      @media only screen and (#{$type}-width: $width) {
          @content;
      }
  } @else {
      @warn 'No hay un tamanio #{$width} definido';
  }
}

// Meadia Queries for landscape
@mixin mq-l($width, $type: max){
  $width: map_get($breakpoints, $width);
  @media (#{$type}-width: $width) and (orientation: landscape) {
      @content;
  }
}
```

The map of Breakpoints

```scss
$breakpoints: (

  phone-xs:   320px,    
  phone-sm:   375px,  
  phone-md:   420px,
  phone-lg:   520px,
  phone-xl:   640px,
  phone-xxl:  813px,

  tablet-sm:  850px,
  tablet-md:  950px,
  tablet-lg:  1050px,

  desk-sm:    1140px,
  desk-md:    1280px,
  desk-lg:    1440px, 
  desk-xxl:   1680px,

);
```

The inlcude example Mixin

```scss
@include mq(phone-xxl, max) {
    @content;
}
```
